const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOG_OUT = "LOG_OUT";

const ROOMS_FETCHED = "ROOMS_FETCHED";
const FETCH_ROOMS = "FETCH_ROOMS";
const ROOM_ADDED = "ROOM_ADDED";
const REMOVE_ROOM = "REMOVE_ROOM";

const FETCH_ROOM = "FETCH_ROOM";
const ROOM_FETCHED = "ROOM_FETCHED";
const ROOM_SELECTED = "ROOM_SELECTED";
const ADD_ITEM = "ADD_ITEM";
const REMOVE_ITEM = "REMOVE_ITEM"; 
const ADD_PAYEE = "ADD_PAYEE";
const REMOVE_PAYEE = "REMOVE_PAYEE";

const MODAL_SHOW = "MODAL_SHOW";
const MODAL_HIDE = "MODAL_HIDE";

export {
    LOGIN_SUCCESS, 
    LOG_OUT,

    ROOMS_FETCHED,
    FETCH_ROOMS, 
    ROOM_ADDED, 
    REMOVE_ROOM,

    FETCH_ROOM,
    ROOM_FETCHED,
    ROOM_SELECTED,
    ADD_ITEM,
    REMOVE_ITEM,
    ADD_PAYEE,
    REMOVE_PAYEE,

    MODAL_SHOW, 
    MODAL_HIDE
};